# NumPy I - introduction

NumPy is the universal standard for working with numerical data in Python, and it’s at the core of the scientific Python and PyData ecosystems.

To access NumPy and its functions import it in your Python code like this:

In [ ]:
import numpy as np

<div class="alert alert-block alert-info">
<b>Tip: </b>When library name is too long for repeated using, while importing, an alias name for it could be defined by using a keyword <code>as</code> and abbreviated word. For numpy, a standard is to use abbreviation <code>np</code>.
</div>

# Creating arrays

The NumPy ndarray class is used to represent both matrices and vectors. A vector is an array with a single dimension (there's no difference between row and column vectors), while a matrix refers to an array with two dimensions. For 3-D or higher dimensional arrays, the term tensor is also commonly used.

<div class="alert alert-block alert-warning">
<b>Example: </b>Create a NumPy array containing the exam scores of five students. Check the array's dimensions, shape, size, and data type. Calculate the average score.
</div>

In [ ]:
scores = np.array([78, 85, 92, 67, 88])

print("Array:", scores)
print("Number of dimensions:", scores.ndim)
print("Shape:", scores.shape)
print("Number of elements:", scores.size)
print("Data type:", scores.dtype)

print("Average score:", np.mean(scores))

<div class="alert alert-block alert-success">
<b>Task: </b>Create a two-dimensional NumPy array containing temperature measurements (in °C) recorded at three weather stations over four days. Explore its properties and calculate the average temperature for each station. Use <code>np.mean</code>.
</div>

In [ ]:
# Rows represent weather stations; columns represent days
temperatures = np.array([
    [18.5, 20.0, 21.5, 19.0],
    [22.0, 23.5, 24.0, 21.5],
    [15.0, 16.5, 18.0, 17.0]])

### Write your code here###

<div class="alert alert-block alert-info">
<b>Tip: </b>If you need a column or a row vector, add another dimension to the array, by explicitly changing the shape (inplace change) or by using <code>np.newaxis</code> (no inplace change; see below).
</div>

In [ ]:
a1 = np.array([0, 1, 2, 3])
a1.shape = (4,1)
a1

OR

In [ ]:
a1 = np.array([0, 1, 2, 3])
a1[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3]])

For later use, assign to the new variable.

In [ ]:
a2 = a1[:, np.newaxis]

## Data types

All of the elements in a NumPy array should be homogeneous. The type of its elements is defined through `dtype` attribute. By default, NumPy tries to infer `dtype` from an array, but it can be specified while defining. Use convertible strings or `dtype` objects for specifying the type of array elements.

In [ ]:
a = np.array([0, 1, 2, 3])
b = np.array([0, 1, 2, 3], dtype='float64')
a, b

(array([0, 1, 2, 3]), array([0., 1., 2., 3.]))

In [ ]:
c = np.array(['Hello', 'world', '!'])
c.dtype # see inferred convertible string for array of strings

dtype('<U5')

For more information on dtype and convertible strings use the __[dtype documentation](https://numpy.org/doc/stable/reference/arrays.dtypes.html)__.

# Common arrays

The most common NumPy array creation functions:

<code>np.zeros</code> → creates an array filled with zeros

<code>np.ones</code> → creates an array filled with ones

<code>np.eye</code> → creates an identity matrix

<code>np.full()</code> → creates an array filled with a specified value

<code>np.empty()</code> → creates an uninitialized array

<div class="alert alert-block alert-warning">
<b>Example: </b>Create a vector and use its values as the main diagonal elements of a diagonal matrix.
</div>

In [ ]:
d = np.diag(np.array([1, 2, 3, 4]))
print(d)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


<div class="alert alert-block alert-warning">
<b>Example: </b>Extract only diagonal elements from the matrix above.
</div>

In [ ]:
d = np.diag(d)
print(d)

<div class="alert alert-block alert-info">
<b>Tip: </b>If you need evenly spaced values within a given interval with a specific spacing between values (e.g., even number) use <code>np.arange</code>, and if you need the exact number of points in the interval, use <code>np.linspace</code>.
</div>

<div class="alert alert-block alert-warning">
<b>Example: </b>Create an array containing six evenly spaced values between 0 and 10. Then create an array of 100 evenly spaced values between 0 and 2π.
</div>

In [ ]:
x = np.linspace(0, 10, 6)
print(x)

angles = np.linspace(0, 2 * np.pi, 100)
print(angles)

array([1, 3, 5, 7])

<div class="alert alert-block alert-success">
<b>Task: </b>Create an array of evenly spaced values between 0 and 1 with step 0.1.
</div>

In [ ]:
#solution

<div class="alert alert-block alert-warning">
<b>Example: </b>Create an array of integers from 0 to 5 and reshape it to the 3 x 2 matrix.
</div>

In [ ]:
e = np.arange(6)
print(e) #vector

e = e.reshape((3, 2))
print(e) #matrix

[0 1 2 3 4 5]


The `numpy.meshgrid()` function is used to create a rectangular grid out of two given one-dimensional arrays representing the Cartesian indexing or Matrix indexing.

<img src="https://i.stack.imgur.com/8Mbig.png" alt="A meshgrid" title="A meshgrid" />

<div class="alert alert-block alert-warning">
<b>Example: </b>Suppose a shop sells products at different prices, and we want to calculate the total cost for different quantities.
</div>

In [ ]:
quantities = np.array([1, 2, 3, 4])
prices = np.array([10, 20, 30])

Q, P = np.meshgrid(quantities, prices)

total = Q * P

<code>np.meshgrid()</code> creates a grid containing every possible combination of quantities and prices.

rows = different prices

columns = different quantities

each cell = price × quantity

The resulting <code>total</code> array shows the cost for each combination

In [ ]:
print(total)

# NumPy random

In [ ]:
np.random.seed(1234)  # Setting the random seed to obtain reproducible results

In [ ]:
a = np.random.rand(4)   # uniform in [0, 1]
print(a)

[0.19151945 0.62210877 0.43772774 0.78535858]


In [ ]:
b = np.random.randn(4)   # Gaussian
print(b)

[-0.72058873  0.88716294  0.85958841 -0.6365235 ]


<div class="alert alert-block alert-info">
<b>Tip: </b>It is recommended to use Random Generator for seeding NumPy random arrays. Use <code>numpy.random.default_rng()</code> as described <a href="https://numpy.org/doc/stable/reference/random/generator.html">here</a>.
</div>

<div class="alert alert-block alert-success">
<b>Task: </b>Create random population of integers and subsample it on random. Use the documentation for solving the task.
</div>

In [ ]:
# solution

# Numerical operations on arrays

All arithmetic operations are elementwise.

<div class="alert alert-block alert-warning">
<b>Example: </b>Create an array. Add 1 to each element and use its values as exponents of 2, element by element.
</div>

In [ ]:
a = np.array([1, 2, 3, 4])
print('a = ', a)
print('a + 1 = ', a+1)
print('2**a = ', 2**a)

a =  [1 2 3 4]
a + 1 =  [2 3 4 5]
2**a =  [ 2  4  8 16]


<div class="alert alert-block alert-success">
<b>Task: </b>Create an all-ones array, add 1 to all of its values and subtract it from the array from the previous example. Use brackets. Print final result.
</div>

In [ ]:
#solution

<div class="alert alert-block alert-danger">
<b></b>Array multiplication is not matrix multiplication!
</div>

Create an all-ones matrix and compare the results of using the `*` operator and the <code>np.dot()</code> function for matrix multiplication.

<div class="alert alert-block alert-success">
<b>Task: </b>Discuss what is "real" matrix multiplication.
</div>

In [ ]:
d = np.ones((3, 3))
print('d')
print(d)

d
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print('d * d')
print(d * d)

d * d
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print('d.dot(d)')
print(d.dot(d))

d.dot(d)
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


# Functions

There are some special functions in NumPy, performed element-wise on the passed array.

<div class="alert alert-block alert-success">
<b>Task: </b>Create a 2D grid for x and y ranging from -5 to 5 with a step of 0.1. Use <code>np.meshgrid()</code> to calculate:
    $$ z=\sin(x^2+y^2) $$
</div>

In [ ]:
#solution